# Basic site settings
title: "Scholarn"                    # Title of your blog
description: "An online platform for education."  # Description for meta tags
baseurl: ""                                 # Leave blank for GitHub Pages
url: "https://scholarn.github.io"       # Your GitHub Pages URL

# Author information
author: "Md Azaharuddin"

# Jekyll theme
theme: minima                               # Use the Minima theme

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed                            # Generates an RSS feed
  - jekyll-seo-tag                         # Adds SEO tags to the site
  - jekyll-sitemap
# Pagination settings (optional)
paginate: 5                                 # Number of posts per page
paginate_path: "/page:num/"     # Path for paginated pages
