title: Scholarn
subtitle: "School To Learn"
description: "Online School To Learn From Anywhere"

baseurl: ""
url: "scholarn.github.io"

author:
  name: "Md Azaharuddin"

lang: "en"
timezone: "Asia/Kolkata"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
  - scope:
      path: ""
      types: "pages"
    values:
      layout: "single"

permalink: pretty
header_pages:
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5 # amount of posts to show
paginate_path: /page:num/
