baseurl: ""
url: "scholarn.github.io"
title: Scholarn
author:
  name: Md Azaharuddin
  email: your-email@domain.com

description: "Best Educationl Website."
lang: "en"
timezone: "Asia/Kolkata"

theme: minimal-mistakes-jekyll

header_pages:

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

jekyll_admin:
  username: admin
  password: secret
