# Basic site settings
title: "Scholarn"
description: "An online Educational Platform."
baseurl: ""
url: "https://scholarn.github.io"
permalink: pretty
# Author information
author: "Md Azaharuddin"

# Jekyll theme
theme: minima
defaults:
  - 
    scope:
      path: ""
    values:
      layout: default

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed                            # Generates an RSS feed
  - jekyll-seo-tag                         # Adds SEO tags to the site
  - jekyll-sitemap
# Pagination settings (optional)
paginate: 5                                 # Number of posts per page
paginate_path: "/page:num/"     # Path for paginated pages
