title: Scholarn
subtitle: "Learn Anywhere"
description: "Best Educationl Website."

baseurl: ""
url: "scholarn.github.io"

author:
  name: Md Azaharuddin

lang: "en"
timezone: "Asia/Kolkata"
permalink: pretty

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
  - scope:
      path: ""
      types: "pages"
    values:
      layout: "single"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-scholar

paginate: 5 # amount of posts to show
paginate_path: /page:num/
